name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run test
        run: |
          pytest ./test-exercice/test-operations.py

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login
        run: |
          docker login --username ben8t --password ${{secrets.GH_PAT}} ghcr.io

      - name: Build Docker image
        run: docker build -t ghcr.io/ben8t/ml_orchestration:latest ./test-exercice

      - name: Push Docker image
        run: docker push ghcr.io/ben8t/ml_orchestration:latest
